name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.20"
          - "1.19"
          - "1.18"
    name: Build
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Test
        run: |
          go test -race -v ./... 2>&1 | go-junit-report -iocopy -set-exit-code -out report.xml

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: ./report.xml
        if: always()
